CREATE TABLE IF NOT EXISTS alumnos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  matricula TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  qr_code TEXT NOT NULL UNIQUE,
  auto_placa TEXT,
  activo INTEGER NOT NULL DEFAULT 1,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accesos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  alumno_id INTEGER NOT NULL,
  matricula TEXT NOT NULL,
  nombre TEXT NOT NULL,
  placa TEXT,
  qr_code TEXT NOT NULL,
  tipo TEXT NOT NULL CHECK(tipo IN ('ENTRADA', 'SALIDA')),
  fecha_hora DATETIME DEFAULT CURRENT_TIMESTAMP,
  estatus TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  FOREIGN KEY (alumno_id) REFERENCES alumnos(id)
);